// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUSb-NWMZKAuM96Kl49mC7sPiJOjXRp8',
    appId: '1:593151144938:web:941f35d66386bcdb4e7893',
    messagingSenderId: '593151144938',
    projectId: 'zypto-25b1a',
    authDomain: 'zypto-25b1a.firebaseapp.com',
    storageBucket: 'zypto-25b1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbPfHsm9ikar0PHBuYJny4Fo_ot3kVyEU',
    appId: '1:593151144938:android:12871d4cc15cb1b04e7893',
    messagingSenderId: '593151144938',
    projectId: 'zypto-25b1a',
    storageBucket: 'zypto-25b1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_mErEig-uYN31AL60VlJ1jjs6GC7sIc8',
    appId: '1:593151144938:ios:758baf61ed79899b4e7893',
    messagingSenderId: '593151144938',
    projectId: 'zypto-25b1a',
    storageBucket: 'zypto-25b1a.firebasestorage.app',
    iosBundleId: 'com.example.zypto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_mErEig-uYN31AL60VlJ1jjs6GC7sIc8',
    appId: '1:593151144938:ios:758baf61ed79899b4e7893',
    messagingSenderId: '593151144938',
    projectId: 'zypto-25b1a',
    storageBucket: 'zypto-25b1a.firebasestorage.app',
    iosBundleId: 'com.example.zypto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcUSb-NWMZKAuM96Kl49mC7sPiJOjXRp8',
    appId: '1:593151144938:web:5bef1cb5805bb69f4e7893',
    messagingSenderId: '593151144938',
    projectId: 'zypto-25b1a',
    authDomain: 'zypto-25b1a.firebaseapp.com',
    storageBucket: 'zypto-25b1a.firebasestorage.app',
  );
}
